### ISSUE TITLE
deliveryBhavcopy Encoding Error

### ISSUE THREAD

**Issue by kmadhyan** [BennyThadikaran/NseIndiaApi#1]
Hi Benny,

Thanks for the Wonderful API. Observed the issue in deliveryBhavcopy.

Error

Download error. Try again later: ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(271 bytes read, 138 more expected)', IncompleteRead(271 bytes read, 138 more expected)))

Kindly check it once please.

Thanks
Kmadhyan

**Comment by BennyThadikaran** [comment]
Hi @kmadhyan 

The error indicates that the report is unavailable. NSE reports are usually available after 7pm. If you tried to download today's report it would result in the error you mentioned.

I would strongly suggest to update to the latest version. Run `pip install -U nse`

My latest commit 8d704c29861a66ef927bd1387b3a6fb025abcf04 handles this early and prints a more useful message to user.
![EOD2 screenshot](https://user-images.githubusercontent.com/19973418/279067982-2cb342b5-7212-4c14-b12f-136e68685b1d.png)

If you want more details on this error, see BennyThadikaran/eod2#59

Thanks for the using NseIndiaApi, let me know if this solved it for you.

Lastly if you are looking for End of Day NSE data i suggest you check my repo [BennyThadikaran/eod2](https://github.com/BennyThadikaran/eod2).

**Comment by BennyThadikaran** [comment]
I have just released the final edits to `nse` package `v0.2.6`. I also added an example on **Catching errors** in the [README usage](https://github.com/BennyThadikaran/NseIndiaApi#-usage) section.
