### ISSUE TITLE
fnobhavcopy download not working

### ISSUE THREAD

**Issue by akshay-bs** [BennyThadikaran/NseIndiaApi#2]
While trying to download the fno bhavcopy I always get this error
RuntimeError('NSE file is unavailable or not yet updated.')

I am able to download the bhavcopy before 8 July.

**Comment by BennyThadikaran** [comment]
Hi Akshay-bs,

The FNO bhavcopy report file and format has changed. It now uses the Udiff file format.

Thanks for reporting it. I will make changes tomorrow and get back to you. 

Meanwhile you may want to take a look at the F&O Udiff common bhavcopy file at <https://www.nseindia.com/all-reports-derivatives>

The file format has changed, so your script will need to be modified to continue working properly.

**Comment by BennyThadikaran** [comment]
Its working now. Run `pip install -U nse` to update to latest version 1.0.1. 

Make sure to update your scripts as the column names are changed in the new Udiff format.

**Comment by akshay-bs** [comment]
It working for me now, thank you for the quick resolution
