### ISSUE TITLE
RuntimeError('NSE file is unavailable or not yet updated.')

### ISSUE THREAD

**Issue by prakasharyaman** [BennyThadikaran/NseIndiaApi#3]
### When i run this sweet piece of code, i get this error.!        :(

_RuntimeError('NSE file is unavailable or not yet updated.')_

``` 
from nse import NSE
from datetime import datetime

with NSE("C:/Users/jugie/download/ss/les") as nse:
    try:
        bhavFile = nse.equityBhavcopy(date=datetime.now())
        dlvFile = nse.deliveryBhavcopy(date=datetime.now())
        raise RuntimeError('Some error')  # force an exception
    except RuntimeError as e:
        # continue execution or exit the script
        print(repr(e))

    # execution continues if handled without exit
    actions = nse.actions()

# NSE request session closed - continue processing
```

**Comment by BennyThadikaran** [comment]
The current day bhavcopy is only available after 7pm Indian time. Pass a date for any past sessions and it should download bhavcopy for that session correctly.

Run this code today after 7pm today and it should work.
Regards,
Benny Thadikaran

**Comment by prakasharyaman** [comment]
Oh ! now i get it .
![oops](https://github.com/user-attachments/assets/7b399506-d0e0-478a-b7a0-f84f7c04ec42)
Thanks !
the lib is awesome af 10/10.
